In [31]:
import warnings
warnings.filterwarnings('ignore')

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
from sklearn.datasets import load_digits
digits = load_digits()

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [35]:
from sklearn.model_selection import train_test_split as tts
X_train,X_test,y_train,y_test = tts(digits.data,digits.target,test_size = 0.3)

In [37]:
# Creating a function to return scores of different algorithms
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [45]:
print('Logistic Regression :',get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
print('Support Vector Classifier :',get_score(SVC(),X_train,X_test,y_train,y_test))
print('Random Forest Classifier :',get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

Logistic Regression : 0.9093959731543624
Support Vector Classifier : 0.4597315436241611
Random Forest Classifier : 0.9228187919463087


In [46]:
# Implementing Cross validation Score functionality of sklearn library manually
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
scores_logistic = []
scores_svm = []
scores_randomforest = []

for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index], \
                                    digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_randomforest.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [53]:
print('Logistic Regression : ',scores_logistic)
print('Support Vector Classifier : ',scores_svm)
print('Random Forest Classifier : ',scores_randomforest)

Logistic Regression :  [0.8953488372093024, 0.9499165275459098, 0.9093959731543624]
Support Vector Classifier :  [0.39368770764119604, 0.41068447412353926, 0.4597315436241611]
Random Forest Classifier :  [0.9302325581395349, 0.9248747913188647, 0.9093959731543624]


In [54]:
# Simplest way - using sklearn directly
from sklearn.model_selection import cross_val_score
print(cross_val_score(LogisticRegression(),digits.data,digits.target))
print(cross_val_score(SVC(),digits.data,digits.target))
print(cross_val_score(RandomForestClassifier(),digits.data,digits.target))

[0.89534884 0.94991653 0.90939597]
[0.39368771 0.41068447 0.45973154]
[0.88538206 0.9081803  0.92785235]
